---
liquid: true
layout: lesson
category: artificial-intelligence
lesson: 1
---
= Introduction to Artificial Intelligence

The day before Valentine's Day 2018, the BBC published an article by Dave Lee titled _link:++http://www.bbc.com/news/technology-43037899++[UK unveils extremism blocking tool]_, describing a tool created to detect IS propagandist videos.

The news was quickly picked up by Inverse, an Amerian online tech magazine for young millenials.
Their headline was significantly more exciting: _link:++https://www.inverse.com/article/41273-uk-company-creates-algorithm-to-flag-propaganda++[A.I. Algorithm Recognizes Terrorist Propaganda with 99 Percent Accuracy]_.

The more sensational headline from Inverse was link:++https://www.reddit.com/r/Futurology/duplicates/7xha9m/ai_algorithm_recognizes_terrorist_propaganda_with/++[shared across ten communities on reddit].
It gained particular traction on link:++https://www.reddit.com/r/Futurology/++[/r/Futurology], a subreddit -- community -- for redditors interested in new technologies.

There's a number of questions that you might have here, and we'll address them in time.
For now, we'll address _why_ this is considered artificial intelligence.

What, to you, does artificial intelligence mean?

Is that the right question to ask?

== Asking the Right Questions

One thing that often comes up with artificial intelligence is that all questions are not created equally.
_"What does artifical intelligence mean?"_ is far too vague and leads us nowhere.
While it is the obvious question to ask, it gives us no data to work with.

Consider instead some classification: from some list of problems, what problems would you consider to be for artificial intelligence?

[cols="1,1,1,1"]
|===
|Parsing Written Textfootnote:[scanning written text and turning it into text you can manipulate on a screen]
|link:++https://en.wikipedia.org/wiki/Travelling_salesman_problem++[Travelling Salesman]footnote:[finding the fastest way to visit every city in a network of cities and highways that connect them]
|Theorem Validatorfootnote:[proving mathematical lemmas]
|Diagnosing Diseases
|Self-Driving Cars
|Legal Document Searchfootnote:[searching for precedent in cases; legal systems require impeccable definitions]
|Language Processingfootnote:[figuring out, for example, the exact meaning of a sentence or paragraph or entire text]
|Page Rankingfootnote:[google]
|Decentralized Bankingfootnote:[cryptocurrencies]
|Mid-Flight Autopilotfootnote:[handing over the controls in the middle of a flight in a plane or space shuttle]
|Cryptography
|Quantum Key Distributionfootnote:[cryptography, but quantum]
|Playing Go
|Playing Tic-Tac-Toe
|Automated Drones
|
|===

Here's what most of us might come up with:
|===
|Just an Algorithm|Artificial Intelligence

|Travelling Salesmanfootnote:[while the actual problem statement indicates that we want the _best possible_ route, by relaxing the contraints to a _reasonably fast_ route this turns into an AI problem.]
|Parsing Written Text
|Legal Document Searchfootnote:[this is essentially keyword search considering the pedancy of legality; however, extending the problem statement to include contextual searches turns this into an AI problem: specifically, that of language processing.]
|Theorem Validator
|Decentralized Banking
|Diagnosing Diseasesfootnote:[for all diseases that we know of, this would certainly be an AI problems; however, if we restrict the constraints to just include common diseases (common cold, flu, stomach ulcers), this could easily switch into the "just an algorithm" category.]
|Mid-Flight Autopilotfootnote:[unless you include things like evasive maneuvers for unexpected missile attacks, mid-flight piloting is just comparing the wind to your flight trajectory and adjusting accordingly.]
|Self-Driving Cars
|Cryptography
|Language Processing
|Quantum Key Distribution
|Page Ranking
|Playing Tic-Tac-Toe
|Playing Go
|
|Automated Drones
|===

Now that we have some data, we can continue our inquiry.
What's common with all those that we decided were artificial intelligence, but not with those we decided were just an algorithm?

One factor that might eventually come to mind is the precision of every part of the problem.

In all of the problems on the left column, there is an absolute "right answer," or at least an absolute "right method" to achieving a goal.
A solution to the travelling salesman problem must be the shortest path; any method for quantum distribution of cryptographic keys must be unbreakable; tic-tac-toe is a game with a link:++https://xkcd.com/832/++[mathematical strategy that never loses].
The important features of these problems are absolutely precise.
There are no extraneous questions to be asked.

But there is always some sort of ambiguity when it comes to problems on the right side.

Some things look very similar on paper, like 1 and l, or l and I.
Sometimes you can tell the difference based on the typeface -- for example, there'd be no ambiguity if it were written in cursive -- but oftentimes written text is simply unclear.
How do we recognize cursive Q's when they look like exactly like fancy 2's?
There's more factors that we need to consider than how characters look.
There are extraneous questions we need to ask.
There are features of this problem that are ambiguous.

There isn't a "perfect" way to drive a car that's better than all other ways.
There's many factors to consider when rating how well a car is driven: speed and safety are only the most obvious.
What about comfort?
What about gas consumption?
What about trolley problem scenarios?
Obviously there's a difference between driving badly and driving well, but there isn't a clear one between driving well and driving great.
There are extraneous questions we need to ask.
Many features of this problem are ambiguous.

Go is a board game where you put stones on a nineteen-by-nineteen grid.
While it is _theoretically_ possible to enumerate every single strategy to find the single best one, there are 361 moves on the first turn, 360 on the second, and this goes on. This makes for more than \(361!\) possible gamesfootnote:[not exactly: every turn, one stone is placed in an empty spot; however, stones can be "captured," which frees up spots, so the number of games can't just be calculated by a factorial], which is larger than \(1.4\times10^{768}\).
For an idea of scale, there's about \(10^{80}\) atoms in the visible universe.
It's impossible to practically compute the absolute best strategy.

So while the conditions for success are precise -- end up with more territory than your opponent -- in practice we can't compute that.
We need to find another way to find a strategy.
There are extraneous questions we need to ask.
By necessity, any strategy must consider features of this problem that are ambiguous.

And here is where we arrive at a workable definition for artificial intelligence:

artificial intelligence:: _n._ a field of techniques used to solve problems with ambiguous, unclear features.