---
layout: landing
category: artificial-intelligence
schedule:
  introduction-to-artificial-intelligence: 21 Mar 2018
  the-expert-system: 7
  the-ai-winter: 7
  k-nearest-neighbours: 7
  decision-trees: 7
  neural-networks: 7
  evolutionary-algorithms: 7
---
= Artificial Intelligence

artificial intelligence, AI:: _n._ the theory and development of computer systems able to perform tasks that normally require human intelligence, such as visual perception, speech recognition, decision-making, and translation between languages.

Artificial intelligence is an ill-defined term referring to a vast scope of technologies.
In this subclub, we will explore the history of artificial intelligence, taking a look at expert systems and early AI before diving into the more recent field of machine learning and modern developments in it.

This subclub is intended to be beginner-friendly; while there will be some coding involved for those who have such experience, it will only be a small part of the overall course.