---
layout: landing
category: artificial-intelligence
schedule:
  introduction-to-artificial-intelligence: 31 Dec 1969
  the-expert-system: 1 Jan 1970
  video-games: 2 Jan 1970
  intelligence: 3 Jan 1970
  learning: 4 Jan 1970
  intractability: 5 Jan 1970
  decision-trees: 6 Jan 1970
  neural-networks: 7 Jan 1970
  evolutionary-algorithms: 8 Jan 1970
---
= Artificial Intelligence

artificial intelligence, AI:: _n._ the theory and development of computer systems able to perform tasks that normally require human intelligence, such as visual perception, speech recognition, decision-making, and translation between languages.

Artificial intelligence is an ill-defined term referring to a vast scope of technologies.
In this subclub, we will explore the history of artificial intelligence, taking a look at expert systems and early AI in video games before diving into the more recent field of machine learning and modern developments in it.

This subclub is intended to be beginner-friendly; while there will be some coding involved for those who have such experience, it will only be a small part of the overall course.