---
layout: landing
category: artificial-intelligence
schedule:
  introduction-to-artificial-intelligence: 21 Mar 2018
  the-expert-system: 4 Apr 2018
  the-ai-winter: 11 Apr 2018
  k-nearest-neighbours: 18 Apr 2018
  intractability: 25 Apr 2018
  decision-trees: 2 May 2018
  neural-networks: 9 May 2018
  evolutionary-algorithms: 23 May 2018
  bayesian-networks: 30 May 2018
  competence: 6 Jun 2018
  prospects: 13 Jun 2018
---
= Artificial Intelligence

artificial intelligence, AI:: _n._ the theory and development of computer systems able to perform tasks that normally require human intelligence, such as visual perception, speech recognition, decision-making, and translation between languages.

Artificial intelligence is an ill-defined term referring to a vast scope of technologies.
In this subclub, we will explore the history of artificial intelligence, taking a look at expert systems and early AI before diving into the more recent field of machine learning and modern developments in it.

This subclub is intended to be beginner-friendly; while there will be some coding involved for those who have such experience, it will only be a small part of the overall course.