---
liquid: true
layout: lesson
category: artificial-intelligence
lesson: 1
---
= The Expert System

expert system:: a computer system that emulates the decision-making ability of a human expert.

You are a computer-part manufacturer.
Your customers have many requests for their computers: they want them to be fast, to be able to hold plenty of memory in RAM; they might want both an SSD and an HDD; they might want a capable graphics card and adequate interfaces with external hardware.
But each every component in your inventory is only compatible with certain models of motherboards, and given the hundreds of models of parts you have, you need experts to handle these requests, which you get many times a day.
If only you could automate the process of coming up with compatible configurations...

Or maybe you run a busy hospital -- the only hospital -- in a large city.
And despite the funds you receive, your hospital is always overcrowded; you can't just buy the land the neighbouring skyscraper rests on, after all.
You get many, many outpatients who only have a cold or a scratch and just need to get a prescription filled out, requiring a diagnosis by a doctor.
And oftentimes, those with more serious ailments are misdiagnosed, considering how much time your limited doctors must work.
If only you could automate the process of diagnosis and triage...

First developed in the 1970's, the *expert system* was the first successful AI schema.
These usually take the form of decision trees: if-then clauses that take some input -- _"I have these symptoms..."_ -- and give you the output that an expert would come to: _"You most likely have this affliction, but here are some other possible issues that can be narrowed down with these tests..."_.

- Expert systems in graphs
- Expert systems in bayesian networks/markov chains